services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    container_name: n8n
    labels:
      - "autokuma.enabled=true"
      - "autokuma.group=n8n"
      - "autokuma.name=n8n Automation"
      - "autokuma.url=http://localhost:5678"
      - "autokuma.type=http"
    ports:
      - "5678:5678"
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_PORT=5678
      - N8N_SECURE_COOKIE=false
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      - TZ=Asia/Kolkata
      - GENERIC_TIMEZONE=Asia/Kolkata
