services:
  speedtest:
    container_name: speedtest
    image: ghcr.io/librespeed/speedtest:latest
    restart: always
    ports:
      - "30093:8080"
    volumes:
      - ./Speed_dataStore:/database
    environment:
      MODE: standalone
      DISTANCE: km
      TITLE: "Kushvinth's Speedtest"
      TELEMETRY: "true"
      ENABLE_ID_OBFUSCATION: "true"
      PASSWORD: ${PASSWORD}
      EMAIL: "Kushvinth.m@gmail.com"
      