version: "3.8"

services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft-server
    labels:
      - "autokuma.enabled=true"
      - "autokuma.group=minecraft"
      - "autokuma.name=Minecraft Server"
      - "autokuma.type=docker"
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.8"
      MEMORY: "2G"
      MAX_TICK_TIME: "-1"
      ENABLE_AUTOSTOP: "TRUE"
      AUTOSTOP_TIMEOUT_EST: "60"
      AUTOPAUSE_KNOCK_INTERFACE: "eth0"
    volumes:
      - ./paperMC:/data
    restart: unless-stopped
  playit:
    image: ghcr.io/playit-cloud/playit-agent:0.16
    container_name: playit
    network_mode: host
    labels:
      - "autokuma.enabled=true"
      - "autokuma.group=minecraft"
      - "autokuma.name=PlayIt Tunnel"
      - "autokuma.type=docker"
    environment:
      - SECRET_KEY=${SECRET_KEY}
