version: "3"
services:
  app:
    image: macarooniman/auto-mcs:latest
    container_name: auto-mcs
    stdin_open: true
    tty: true
    restart: unless-stopped

    environment:
      WEB_PORT: "8180"
      WEB_USERNAME: ${MC_USER}
      WEB_PASSWORD: ${MC_PASS}
    env_file:
      - ".env"
    ports:

      # Web interface (make this the same as WEB_PORT)
      - "8180:8180"

      # Telepath API (auto-mcs)
      - "7001:7001"

      # Add more ports based on the servers you create
      - "25565:25565"

    volumes:
      - ./auto-mcs-data:/root/.auto-mcs

volumes:
  auto-mcs-data:
